name: 101 DATES
favicon: null
layout_spectrum: 0.23528366559185088
typography_spectrum: 0.19108187477104366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06687745894305408
  lightness: 0.6107425931841135
  saturation: 0.534969920059666
  rhythmicContrast: 0.45869602146558464
purpose: []
